services:
  inspektor:
    volumes:
      - ./requests/:/usr/src/requests
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - inspektor
    ports:
      - 80:80